# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160528_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
