# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160528_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
