# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Canada/Eastern', max_length=255),
        ),
    ]
